### ISSUE TITLE
Installing glint as regular users

### ISSUE THREAD

**Issue by rdauria** [cozygene/glint#10]
Hello,

Some users of our linux shared cluster would like to use glint, would it be possible to have a more generic install.py that will allow to install glint in the users' $HOME? In order to do so any pip commands can be updated to: 

`
pip install <LIB> --user
`

Not many multi-user systems would consider installing a third-party tool as root, so this generalization should increase utilization of this tool.

Thanks,
RD

**Comment by E-R** [comment]
Definitely makes sense, thanks for the suggestion! Can update for the next release.
For now one can simply install the dependencies one-by-one to user directory (there are just a few, as described in the README).

**Comment by rdauria** [comment]
Hello,

Thanks for getting back to me, I seem to encounter a problem when trying to run glint. Here are the steps:

1) clone glint:

`git clone https://github.com/cozygene/glint.git`

2) change to glint directory and install the dependencies:


```
cd glint
pip install cvxopt --user
pip install sklearn --user
pip install statsmodels --user

```

3) run glint (from the glint directory) with:


`python glint.py `


this is what I get:
```


Validating all dependencies are installed...
Anaconda wasn't found
Checking if required dependencies are installed...
Dependencies are installed
All dependencies are installed
Traceback (most recent call last):
  File "glint.py", line 8, in <module>
    from utils import common
  File "/u/home/systems/dauria/glint/FROM_GIT/glint/utils/__init__.py", line 2, in <module>
    from regression import LinearRegression, LogisticRegression
  File "/u/home/systems/dauria/glint/FROM_GIT/glint/utils/regression.py", line 8, in <module>
    import statsmodels.api as sm
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/api.py", line 5, in <module>
    from . import iolib
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/iolib/__init__.py", line 1, in <module>
    from .foreign import StataReader, genfromdta, savetxt
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/iolib/foreign.py", line 14, in <module>
    from statsmodels.compat.python import (lzip, lmap, lrange,
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 11, in <module>
    from statsmodels.tools.validation import array_like
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/tools/validation/__init__.py", line 1, in <module>
    from .validation import (array_like, bool_like,  dict_like,
  File "/u/home/systems/dauria/.local/lib/python2.7/site-packages/statsmodels/tools/validation/validation.py", line 1, in <module>
    from collections.abc import Mapping
ImportError: No module named abc

```

notice the error appears to be coming when loading common:

`
from utils import common
`

Any idea? 

Thanks

**Comment by E-R** [comment]
Have you tried setting up a new conda environment with python 2.7 and installing the glint dependencies (ideally the same versions specified in the README)? This is probably the easiest way to make sure there are no issues with dependencies like the one you're experiencing.
